import test from 'node:test';
import assert from 'node:assert/strict';
import { Game } from '../public/src/game.js';
import { createLessonScene, LESSONS } from '../public/src/lessons.js';
import { Apprentice, observeForPolicy, legalActions, actionFeatures, decisionExample } from '../public/src/apprentice.js';
import { ApprenticeSession } from '../public/src/apprentice-session.js';
import { taskDone, protectedIntact } from '../public/src/director.js';
import { createScene } from '../public/src/scene.js';
const settle=(g,session)=>{for(let i=0;i<2400;i++){g.update(.05);session?.tick(.05);if(!g.pending&&!g.path.length){for(let k=0;k<15;k++){g.update(.05);session?.tick(.05);}return;}}throw new Error('Failed to settle');};
function demonstration(model,context,seed='teaching-'+context){const g=new Game(createLessonScene(context,seed));
 const seq=context==='linen'?['cupboard','towel-0','fresh-shelf','towel-1','fresh-shelf','finish']:['cup-a',context==='tea'?'tea-tray':'cart-tray','cup-b',context==='tea'?'tea-tray':'cart-tray','finish'];
 for(const id of seq){const e=decisionExample(g,id);assert.ok(id==='finish'?g.finish():g.command(id),g.lastMessage);settle(g);e.completedAt=g.time;model.add(e);}return g;
}
function rollout(model,context,seed){const g=new Game(createLessonScene(context,seed)),trace=[];
 for(let i=0;i<32&&g.status==='playing';i++){const p=model.predict(g);if(p.ask)return {g,trace,reason:p.reason};trace.push(p.action);if(!(p.action.kind==='finish'?g.finish():g.command(p.action.id)))return {g,trace,reason:g.lastMessage};settle(g);}
 return {g,trace};
}
test('every teaching scene and 60 layout variants compile with the existing route checker',()=>{for(const l of LESSONS)for(let i=0;i<20;i++){const g=new Game(createLessonScene(l.id,'variant-'+i));assert.ok(g.plan.proof.ok);assert.equal(g.scene.initialProtected.length,1);}});
test('untrained apprentice explicitly asks, and has no preinstalled routine weights',()=>{const a=new Apprentice(),g=new Game(createLessonScene());assert.ok(a.predict(g).ask);assert.equal(Object.keys(a.weights).length,0);assert.equal(a.examples.length,0);});
test('policy boundary never reads goal fields or a solution plan',()=>{const g=new Game(createLessonScene());for(const o of g.scene.objects)Object.defineProperty(o,'desired',{get(){throw new Error('goal leak');}});Object.defineProperty(g,'plan',{get(){throw new Error('plan leak');}});const obs=observeForPolicy(g);assert.ok(legalActions(obs).length>2);const text=JSON.stringify(obs);for(const term of ['desired','taskDone','required','plan','score','history','completed'])assert.ok(!text.includes('"'+term+'"'));});
test('changing hidden destinations leaves policy observations and candidate scores unchanged',async()=>{const a=new Apprentice();demonstration(a,'collect');await a.train();const g=new Game(createLessonScene()),before=a.predict(g);for(const o of g.scene.objects)if(o.movable)o.desired='tea-tray';g.plan.tasks.reverse();const after=a.predict(g);assert.deepEqual(before.observation,after.observation);assert.deepEqual(before.action,after.action);assert.equal(before.preference,after.preference);});
test('guest protection and DND are independent legal guards, not policy choices',()=>{const a=new Apprentice(),g=new Game(createLessonScene());assert.ok(!legalActions(observeForPolicy(g)).some(a=>a.id==='keepsake'));g.scene.permission='denied';assert.deepEqual(legalActions(observeForPolicy(g)),[]);assert.ok(a.predict(g).ask);});
test('compatible wrong placement is allowed only in teaching sandbox, and cannot satisfy the goal',()=>{const g=new Game(createLessonScene());g.command('cup-a');settle(g);assert.ok(g.command('tea-tray'));settle(g);assert.equal(g.entity('cup-a').location,'tea-tray');assert.equal(taskDone(g.scene,g.plan.tasks[0]),false);assert.equal(g.finish(),false);const ordinary=new Game();ordinary.command('cup-a');settle(ordinary);assert.equal(ordinary.command('tea-tray'),false);});
test('finish remains a candidate before goals are satisfied; mask is not an answer key',()=>{const g=new Game(createLessonScene());assert.ok(legalActions(observeForPolicy(g)).some(a=>a.kind==='finish'));assert.equal(g.finish(),false);});
test('one cup demonstration fits real weights and completes 20 held-out authored layouts',async()=>{const a=new Apprentice();demonstration(a,'collect');assert.equal(a.examples.length,5);await a.train();assert.ok(Object.values(a.weights).some(x=>Math.abs(x)>.1));for(let i=0;i<20;i++){const r=rollout(a,'collect','holdout-cups-'+i);assert.equal(r.g.status,'won',r.reason);assert.equal(r.trace.length,5);assert.ok(protectedIntact(r.g.scene));}});
test('untaught task context asks instead of borrowing the wrong destination',async()=>{const a=new Apprentice();demonstration(a,'collect');await a.train();const p=a.predict(new Game(createLessonScene('tea')));assert.ok(p.ask);assert.match(p.reason,/no teaching example/);});
test('teaching all three requests preserves earlier routines across 60 held-out layouts',async()=>{const a=new Apprentice();for(const c of ['collect','tea','linen'])demonstration(a,c);await a.train();assert.equal(a.examples.length,16);for(const c of ['collect','tea','linen'])for(let i=0;i<20;i++){const {g,trace,reason}=rollout(a,c,'all-holdout-'+i);assert.equal(g.status,'won',reason);assert.equal(trace.length,c==='linen'?6:5);assert.ok(trace.filter(a=>a.kind==='place').every(a=>a.id===(c==='linen'?'fresh-shelf':c==='tea'?'tea-tray':'cart-tray')));}});
test('feature representation is invariant to object IDs, colors and coordinates',()=>{const g=new Game(createLessonScene()),a=observeForPolicy(g),b=structuredClone(a);for(const o of b.objects){o.id='different-'+o.id;o.x+=.3;o.z-=.2;}const af=legalActions(a).map(x=>actionFeatures(a,x)),bf=legalActions(b).map(x=>actionFeatures(b,x));assert.deepEqual(af,bf);});
test('model data export/import yields identical predictions and no imported execution',async()=>{const a=new Apprentice();demonstration(a,'tea');await a.train();const b=Apprentice.fromJSON(JSON.stringify(a.toJSON())),g=new Game(createLessonScene('tea','import'));assert.deepEqual(a.predict(g).action,b.predict(g).action);assert.deepEqual({...a.weights},{...b.weights});assert.equal(g.history.length,0);});
test('bad, oversized and nonfinite notebooks are rejected',async()=>{assert.throws(()=>Apprentice.fromJSON('{'));assert.throws(()=>Apprentice.fromJSON(' '.repeat(2_000_001)));assert.throws(()=>Apprentice.fromJSON({schema:'bad'}));const a=new Apprentice();demonstration(a,'collect');await a.train();for(const damage of [v=>v.weights['<script>']=5,v=>v.weights[Object.keys(v.weights)[0]]=Infinity,v=>v.examples[0].selected=999,v=>v.examples[0].candidates[0][0]='__proto__',v=>v.examples[0].completedAt=null]){const v=a.toJSON();damage(v);assert.throws(()=>Apprentice.fromJSON(v));}});
test('new teaching makes a fitted model stale until explicitly retrained',async()=>{const a=new Apprentice();demonstration(a,'collect');await a.train();demonstration(a,'tea');assert.ok(a.predict(new Game(createLessonScene())).ask);assert.match(a.predict(new Game(createLessonScene())).reason,/New examples/);});
test('teaching requires consent and ordinary practice captures nothing',()=>{const s=new ApprenticeSession(),g=s.attach(new Game(createLessonScene()));assert.throws(()=>s.beginTeaching(false));g.command('cup-a');settle(g,s);assert.equal(s.model.examples.length,0);});
test('teaching records the pre-decision observation only after execution completes',()=>{const s=new ApprenticeSession(),g=s.attach(new Game(createLessonScene()));s.beginTeaching(true);g.command('cup-a');assert.equal(s.model.examples.length,0);settle(g,s);assert.equal(s.model.examples.length,1);assert.equal(s.model.examples[0].observation.robot.held,null);assert.equal(g.robot.held,'cup-a');assert.ok(s.model.examples[0].completedAt>s.model.examples[0].requestedAt);});
test('cancelled and rejected interactions do not turn into successful examples',()=>{const s=new ApprenticeSession(),g=s.attach(new Game(createLessonScene()));s.beginTeaching(true);assert.equal(g.command('keepsake'),false);assert.equal(s.model.examples.length,0);g.command('cup-a');g.cancel();s.tick(.05);assert.equal(s.model.examples.length,0);s.stop();assert.equal(s.consent,false);});
test('undo removes the exact taught execution, but not a later untaught action',()=>{const s=new ApprenticeSession(),g=s.attach(new Game(createLessonScene()));s.beginTeaching(true);g.command('cup-a');settle(g,s);assert.equal(s.model.examples.length,1);g.undo();assert.equal(s.model.examples.length,0);g.command('cup-a');settle(g,s);s.endTeaching();g.command('cart-tray');settle(g,s);g.undo();assert.equal(s.model.examples.length,1);});
test('takeover interrupts the controller, retains cargo and requires fresh teaching consent',async()=>{const a=new Apprentice();demonstration(a,'collect');await a.train();const s=new ApprenticeSession({model:a}),g=s.attach(new Game(createLessonScene('collect','takeover')));g.command('cup-a');settle(g,s);assert.equal(g.robot.held,'cup-a');s.startRun();for(let i=0;i<30;i++){g.update(.05);s.tick(.05);}assert.ok(g.pending||g.path.length);s.takeOver();assert.equal(g.robot.held,'cup-a');assert.equal(g.pending,null);assert.equal(s.consent,false);assert.equal(s.mode,'idle');});
test('a correction is linked to the learner attempt and never collected without opt-in',async()=>{const a=new Apprentice();demonstration(a,'collect');await a.train();const s=new ApprenticeSession({model:a}),g=s.attach(new Game(createLessonScene('collect','correction')));s.startRun();s.takeOver();s.beginTeaching(true);g.command('cup-b');settle(g,s);assert.equal(a.examples.length,6);assert.match(a.examples.at(-1).correctionOf,/attempt-/);assert.equal(a.examples.at(-1).weight,2);});
test('autonomous execution uses ordinary game commands, never adds its own choices as human labels',async()=>{const a=new Apprentice();demonstration(a,'collect');await a.train();const s=new ApprenticeSession({model:a}),g=s.attach(new Game(createLessonScene('collect','autonomous')));s.startRun();for(let i=0;i<5000&&g.status==='playing';i++){g.update(.05);s.tick(.05);}assert.equal(g.status,'won');assert.equal(a.examples.length,5);assert.equal(s.attempts.at(-1).outcome,'completed');assert.ok(g.history.every(h=>h.actor==='apprentice:v1'));});
test('guardian rejection leads to help, not silent retry or fake success',async()=>{const a=new Apprentice();demonstration(a,'collect');await a.train();const s=new ApprenticeSession({model:a}),scene=createLessonScene('collect','reject');for(const o of scene.objects)if(o.movable)o.desired='tea-tray';const g=s.attach(new Game(scene));s.startRun();for(let i=0;i<5000&&!['help','done'].includes(s.mode);i++){g.update(.05);s.tick(.05);}assert.equal(s.mode,'help');assert.equal(g.status,'playing');assert.equal(s.attempts.at(-1).outcome,'execution_rejected');});
test('ordinary campaign retains original non-apprentice behavior',()=>{const s=new ApprenticeSession(),g=s.attach(new Game(createScene('quiet')));assert.ok(g.command('defer-room'));assert.ok(g.finish());assert.equal(s.model.examples.length,0);});

test('successful teacher finish clears teaching consent synchronously',()=>{const s=new ApprenticeSession(),g=s.attach(new Game(createLessonScene()));s.beginTeaching(true);for(const id of ['cup-a','cart-tray','cup-b','cart-tray']){g.command(id);settle(g,s);}assert.ok(g.finish());assert.equal(s.consent,false);assert.equal(s.mode,'idle');assert.equal(s.model.examples.length,5);});

test('notebook imports reject media payloads and forged explanation fields',()=>{const a=new Apprentice();demonstration(a,'collect');for(const change of [v=>v.examples[0].webcam='fake',v=>v.examples[0].observation.rawHands=[],v=>v.examples[0].chosen.role='cart']){const data=a.toJSON();change(data);assert.throws(()=>Apprentice.fromJSON(data));}});
test('new lesson never inherits a correction link from a previous room',async()=>{const a=new Apprentice();demonstration(a,'collect');await a.train();const s=new ApprenticeSession({model:a});s.attach(new Game(createLessonScene()));s.startRun();s.takeOver();assert.ok(s.correction);const g=s.attach(new Game(createLessonScene('tea','another-room')));s.beginTeaching(true);g.command('cup-a');settle(g,s);assert.equal(a.examples.at(-1).correctionOf,null);});
