import test from 'node:test';import assert from 'node:assert/strict';import {once} from 'node:events';
import {buildRequest,generateProposal} from '../server/ai.mjs';import {createServer} from '../server/index.mjs';import {createScene} from '../public/src/scene.js';import {readScene} from '../public/src/director.js';
const proposal={title:'A little welcome',brief:'Collect the hotel cups with care.',taskIds:readScene(createScene()).map(t=>t.id)};
const fake=data=>async()=>({ok:true,json:async()=>data});
const envelope=p=>({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(p)}]}]});
test('Responses request has JSON schema, no storage or tools',()=>{const r=buildRequest(createScene(),'configured-model');assert.equal(r.store,false);assert.equal(r.text.format.strict,true);assert.equal(r.tools,undefined);assert.equal(r.model,'configured-model');});
test('mock provider output is semantically validated',async()=>{const p=await generateProposal({levelId:'welcome',seed:'A',key:'TEST_ONLY',model:'test',fetcher:fake(envelope(proposal))});assert.deepEqual(p,proposal);});
test('refusal, truncation, malformed JSON and unknown IDs are rejected',async()=>{for(const d of [{status:'incomplete',output:[]},{status:'completed',output:[{type:'message',content:[{type:'refusal'}]}]},envelope({...proposal,taskIds:['fake']})])await assert.rejects(generateProposal({levelId:'welcome',seed:'A',key:'TEST_ONLY',model:'test',fetcher:fake(d)}));});
async function server(env={},fetcher=fetch){const s=createServer({env,fetcher});s.listen(0,'127.0.0.1');await once(s,'listening');const base='http://127.0.0.1:'+s.address().port;return {s,base};}
test('static server exposes public assets but not secrets/source server',async()=>{const {s,base}=await server();try{for(const prefix of ['','/goodbot'])for(const f of ['/index.html','/src/app.js','/style.css','/icon.svg']){const r=await fetch(base+prefix+f);assert.equal(r.status,200);}for(const f of ['/server/ai.mjs','/.env','/%2eenv','/src/missing.js'])assert.equal((await fetch(base+f)).status,404);const cfg=await (await fetch(base+'/api/config')).json();assert.equal(cfg.aiEnabled,false);assert.equal(cfg.csrf,null);assert.equal((await fetch(base+'/api/tasks',{method:'POST'})).status,503);}finally{s.closeAllConnections();await new Promise(r=>s.close(r));}});
test('API rejects cross-origin, missing consent and duplicate requests; mock call only',async()=>{let calls=0;const fetcher=async(...a)=>{calls++;return fake(envelope(proposal))(...a);};const {s,base}=await server({GOODBOT_AI_ENABLED:'1',OPENAI_API_KEY:'TEST_ONLY',OPENAI_MODEL:'test'},fetcher);
try{const cfg=await(await fetch(base+'/api/config')).json();assert.equal(cfg.aiEnabled,true);const headers={'Content-Type':'application/json','X-Goodbot-CSRF':cfg.csrf,Origin:base};
assert.equal((await fetch(base+'/api/tasks',{method:'POST',headers:{...headers,Origin:'https://evil.test'},body:JSON.stringify({levelId:'welcome',seed:'A',consent:true})})).status,403);
assert.equal((await fetch(base+'/api/tasks',{method:'POST',headers,body:JSON.stringify({levelId:'welcome',seed:'A',consent:false})})).status,400);
assert.equal((await fetch(base+'/api/tasks',{method:'POST',headers,body:JSON.stringify({levelId:'welcome',seed:'A',consent:true,apiKey:'never'})})).status,400);
const r=await fetch(base+'/api/tasks',{method:'POST',headers,body:JSON.stringify({levelId:'welcome',seed:'A',consent:true})});assert.equal(r.status,200);assert.equal(calls,1);assert.equal((await fetch(base+'/api/tasks',{method:'POST',headers,body:JSON.stringify({levelId:'welcome',seed:'A',consent:true})})).status,429);
}finally{s.closeAllConnections();await new Promise(r=>s.close(r));}});
