import test from 'node:test';import assert from 'node:assert/strict';
import {WASM} from '../public/src/raster-data.js';import {MeshBuilder}from'../public/src/geometry.js';
import {Game}from'../public/src/game.js';import{buildRoom,dynamicRoom}from'../public/src/hotel3d.js';
import{cameraCalibration,renderedPose,virtualState,semanticContacts,EpisodeRecorder,instrumentGame}from'../public/src/recording.js';
import{ContactBench,pressureMap,TACTILE_CONFIG}from'../public/src/tactile.js';import{zipFiles,crc32}from'../public/src/zip.js';
const e=()=>new WebAssembly.Instance(new WebAssembly.Module(Buffer.from(WASM,'base64'))).exports;
function render(engine,b,ao=0){new Float32Array(engine.memory.buffer,engine.vertices(),engine.maxVertices()*9).set(b.v);new Float32Array(engine.memory.buffer,engine.materials(),512).set(b.materials);new Float32Array(engine.memory.buffer,engine.config(),32).set([0,0,3,0,0,0,1,1.25]);engine.render(b.v.length/27,80,80,0,ao);}
test('instance labels follow visible near geometry instead of the rear triangle',()=>{const b=new MeshBuilder();b.material('#fefefe');b.instance=9;b.tri([-1,-1,0],[1,-1,0],[0,1,0],0);b.instance=10;b.tri([-1,-1,-1],[1,-1,-1],[0,1,-1],0);const eng=e();render(eng,b);const labels=new Uint16Array(eng.memory.buffer,eng.labelBuffer(),6400),d=new Float32Array(eng.memory.buffer,eng.depthBuffer(),6400);assert.equal(labels[40*80+40],9);assert.ok(Math.abs(1/d[40*80+40]-3)<1e-5);assert.equal(labels[0],0);});
test('baked label and reciprocal-depth buffers survive empty dynamic frames',()=>{const g=new Game(),{builder:b}=buildRoom(g.scene),eng=e();new Float32Array(eng.memory.buffer,eng.vertices(),eng.maxVertices()*9).set(b.v);new Float32Array(eng.memory.buffer,eng.materials(),512).set(b.materials);new Float32Array(eng.memory.buffer,eng.config(),32).set([9.3,3.5,10.4,5.1,1,4.3,1,1.25]);eng.bake(b.v.length/27,80,80,1,1);const before=new Uint16Array(new Uint16Array(eng.memory.buffer,eng.labelBuffer(),6400));eng.dynamic(0);assert.deepEqual(new Uint16Array(eng.memory.buffer,eng.labelBuffer(),6400),before);assert.ok(before.some(v=>v===2));});
test('slope-compensated AO does not paint a false shadow onto an isolated flat plane',()=>{const b=new MeshBuilder();b.material('#ddddee');b.quad([-5,-5,-2],[5,-5,1],[5,5,1],[-5,5,-2],0);const eng=e();render(eng,b,0);const before=new Uint8Array(new Uint8Array(eng.memory.buffer,eng.image(),6400*4));render(eng,b,1);const after=new Uint8Array(eng.memory.buffer,eng.image(),6400*4);for(let y=12;y<68;y++)for(let x=12;x<68;x++)for(let c=0;c<3;c++)assert.ok(Math.abs(before[(y*80+x)*4+c]-after[(y*80+x)*4+c])<=1);});
test('camera calibration is optical right/down/forward and center ray transforms correctly',()=>{const c=cameraCalibration({eye:[3,2,5],R:[1,0,0],U:[0,1,0],F:[0,0,-1],fov:60,width:640,height:480,view:'robot',backend:'test'});assert.equal(c.K_row_major[2],320);assert.equal(c.K_row_major[5],240);assert.ok(Math.abs(c.K_row_major[0]-415.6921938)<1e-5);assert.deepEqual(c.T_world_camera_optical_row_major,[1,-0,0,3,0,-1,0,2,0,-0,-1,5,0,0,0,1]);assert.equal(c.observation_scope,'virtual_robot_head');});
test('overview recordings explicitly identify privileged observations',()=>assert.equal(cameraCalibration({eye:[0,0,0],R:[1,0,0],U:[0,1,0],F:[0,0,1],fov:60,width:400,height:300,view:'overview'}).observation_scope,'privileged_player_camera'));
test('held-object rendered pose is distinct from its task anchor and rotates with the base',()=>{const g=new Game();g.robot.yaw=Math.PI/2;const o=g.scene.objects[0];o.held=true;const a=renderedPose(g,o);assert.ok(Math.abs(a.position_m[0]-g.robot.x-.49)<1e-6);assert.ok(Math.abs(a.position_m[2]-g.robot.z)<1e-6);assert.equal(a.position_m[1],1.01);});
test('hotel contact relations never fabricate tactile or force measurements',()=>{const g=new Game();for(const c of semanticContacts(g)){assert.equal(c.normal_force_N,null);assert.equal(c.contact_point_world_m,null);assert.equal(c.tactile,null);assert.equal(c.source,'task_state_not_collision_solver');}assert.equal(virtualState(g).robot.joint_torques_Nm,null);assert.equal(virtualState(g).tactile.available,false);});
test('no recording and no action retention before explicit separate consent',()=>{const r=new EpisodeRecorder(),g=instrumentGame(new Game(),r);assert.throws(()=>r.start(g,false),/consent/);g.command('cup-a');assert.equal(r.actions.length,0);assert.equal(r.manifest,null);});
test('input requests are logged after opt-in and bounded independently of rendered frames',()=>{const r=new EpisodeRecorder({limits:{events:2}}),g=instrumentGame(new Game(),r);r.start(g,true);g.command('cup-a');g.command('not-real');g.command('cup-b');assert.equal(r.actions.length,2);assert.equal(r.actions[0].accepted,true);assert.equal(r.actions[1].accepted,false);assert.equal(r.active,false);assert.equal(r.stopReason,'event_limit');});
test('discard resets local metadata, samples and actions',()=>{const r=new EpisodeRecorder(),g=instrumentGame(new Game(),r);r.start(g,true);g.command('cup-a');r.discard();assert.equal(r.active,false);assert.equal(r.manifest,null);assert.equal(r.actions.length,0);assert.equal(r.frames.length,0);});
test('hotel recording stops at its simulation-duration cap',()=>{const r=new EpisodeRecorder({limits:{activeSeconds:.1}}),g=new Game();r.start(g,true);g.update(.05);r.observe(g);assert.equal(r.active,true);g.update(.05);r.observe(g);assert.equal(r.active,false);assert.equal(r.stopReason,'duration_limit');});
test('closed camera images and raw hands are not fields in the episode state',()=>{const g=new Game(),r=new EpisodeRecorder();r.start(g,true);const m=r.manifest;assert.equal(m.privacy.webcam_frames,false);assert.equal(m.privacy.hand_landmarks,false);assert.equal(m.privacy.microphone,false);assert.equal(m.privacy.automatic_upload,false);assert.ok(!JSON.stringify(virtualState(g)).includes('landmarks'));});
test('taxel pressure integrates to the supplied normal force',()=>{for(const force of [0,.1,1.6,3.2])for(const u of [-.004,0,.004]){const p=pressureMap(force,{u});const sum=p.pressure_Pa.reduce((a,v)=>a+v,0)*p.taxel_area_m2;assert.ok(Math.abs(sum-force)<1e-6);assert.equal(p.pressure_Pa.length,256);}});
test('zero contact produces zero pressure and no defined center of pressure',()=>{const a=pressureMap(0);assert.ok(a.pressure_Pa.every(v=>v===0));assert.equal(a.center_of_pressure_local_m,null);});
test('center of pressure is computed from discretized taxels, not copied from requested offset',()=>{const a=pressureMap(2,{u:.004});assert.ok(a.center_of_pressure_local_m[0]>.003);assert.ok(a.center_of_pressure_local_m[0]<.004);assert.ok(Math.abs(a.center_of_pressure_local_m[1])<1e-8);});
test('bench static compression is k delta, not game contact force',()=>{const b=new ContactBench();let s;for(let i=0;i<30;i++)s=b.step(1/60,.002);assert.ok(Math.abs(s.pads[0].normal_force_N-1.6)<1e-8);assert.equal(s.source,'analytic_prescribed_contact_fixture');assert.equal(s.pads[0].shear_force_N,null);assert.deepEqual(s.net_force_on_fixed_object_N,[0,0,0]);});
test('opposing pads have equal force magnitude and opposite world normals',()=>{const b=new ContactBench();const s=b.step(1/60,.002);for(let i=0;i<3;i++)assert.ok(s.pads[0].force_on_fixed_object_world_N[i]+s.pads[1].force_on_fixed_object_world_N[i]===0);assert.deepEqual(s.pads[0].normal_world,[1,0,0]);assert.deepEqual(s.pads[1].normal_world,[-1,0,0]);});
test('prescribed contact transitions separated → begin → persist → end, without tensile force',()=>{const b=new ContactBench();assert.equal(b.step(1/60,0).contact_phase,'separated');assert.equal(b.step(1/60,.0002).contact_phase,'begin');assert.equal(b.step(1/60,.0002).contact_phase,'persist');const s=b.step(1/60,0);assert.equal(s.contact_phase,'end');assert.equal(s.pads[0].normal_force_N,0);});
test('bench command is rate limited and indentation bounded',()=>{const b=new ContactBench();let s=b.step(1/60,1);assert.ok(s.executed_indentation_m<=TACTILE_CONFIG.max_speed_m_per_s/60+1e-8);for(let i=0;i<30;i++)s=b.step(1/60,1);assert.equal(s.executed_indentation_m,.004);assert.throws(()=>b.step(NaN,0));assert.throws(()=>b.step(.2,0));assert.throws(()=>b.step(.01,NaN));});
test('tactile grids reject invalid negative force and oversized arrays',()=>{assert.throws(()=>pressureMap(-1));assert.throws(()=>pressureMap(1,{rows:100000}));assert.throws(()=>pressureMap(Infinity));});
test('CRC32 matches the known check vector',()=>assert.equal(crc32(new TextEncoder().encode('123456789')),0xcbf43926));
test('ZIP entries preserve byte lengths and CRC in local file header',async()=>{const data=new Uint8Array([4,8,15,16,23,42]),blob=await zipFiles([{name:'depth/000000.f32',data}]),bytes=new Uint8Array(await blob.arrayBuffer()),v=new DataView(bytes.buffer);assert.equal(v.getUint32(0,true),0x04034b50);assert.equal(v.getUint32(14,true),crc32(data));assert.equal(v.getUint32(18,true),6);const nameLen=v.getUint16(26,true);assert.deepEqual(bytes.slice(30+nameLen,36+nameLen),data);assert.equal(v.getUint32(bytes.length-22,true),0x06054b50);});
test('ZIP rejects path traversal and absolute paths',async()=>{await assert.rejects(zipFiles([{name:'../evil',data:'x'}]));await assert.rejects(zipFiles([{name:'/evil',data:'x'}]));});
test('no empty episode export is presented as a dataset',async()=>{const r=new EpisodeRecorder();await assert.rejects(r.export(),/No recorded/);});

test('assisted action completions are logged separately from requested commands',()=>{const r=new EpisodeRecorder(),g=instrumentGame(new Game(),r);r.start(g,true);g.command('cup-a');for(let i=0;i<400&&!g.robot.held;i++){g.update(.05);r.observe(g);}assert.equal(r.actions[0].kind,'command');assert.equal(r.executions.length,1);assert.equal(r.executions[0].kind,'pick');assert.equal(r.executions[0].source,'assisted_game_action');r.observe(g);assert.equal(r.executions.length,1);});
test('tactile footprint rejects non-finite dimensions and underflow instead of emitting NaN',()=>{assert.throws(()=>pressureMap(1,{width:Infinity}));assert.throws(()=>pressureMap(1,{sigma:Infinity}));assert.throws(()=>pressureMap(1,{u:1e5}));});

test('capture calibration preserves the original raster intrinsics for exact downsampled rays',()=>{const c=cameraCalibration({eye:[0,0,0],R:[1,0,0],U:[0,1,0],F:[0,0,1],fov:60,width:480,height:300,sourceWidth:960,sourceHeight:600,view:'room'});assert.equal(c.source_raster.width,960);assert.ok(Math.abs(c.source_raster.K_row_major[0]-2*c.K_row_major[0])<1e-8);assert.ok(c.resampling.includes('floor'));});
